baseURL = "/"
languageCode = "en-us"
title = "RainbowLabs Cloud"
themesDir = "themes"
theme = "hero"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "favicon.png"
    mobile_height = "36px"
    mobile_width = "240px"
    desktop = "header_logo.png"
    desktop_height = "64px"
    desktop_width = "240px"
    alt = "RainbowLabs"

  [params.homepage_meta_tags]
    meta_description = "RainbowLabs is a company that specializes in cloud-connected light installations."
    meta_og_title = "RainbowLabs Cloud"
    meta_og_type = "website"
    meta_og_url = "https://cloud.rainbowlabs.de"
    meta_og_image = "https://cloud.rainbowlabs.de/favicon.png"
    meta_og_description = "RainbowLabs is a company that specializes in cloud-connected light installations."

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
